/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2018-12-26 11:06:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>StreetViewRatingApp_HPSCIL@wangjiale</title>\r\n");
      out.write("    <link href=\"css/register.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <script src=\"lib/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("    <link href=\"lib/jquery-easyui-1.5.1/themes/material/easyui.css\" rel=\"stylesheet\" >\r\n");
      out.write("    <link href=\"lib/jquery-easyui-1.5.1/themes/icon.css\" rel=\"stylesheet\" >\r\n");
      out.write("    <link href=\"lib/jquery-easyui-1.5.1/themes/color.css\" rel=\"stylesheet\" >\r\n");
      out.write("    <script src=\"lib/jquery-easyui-1.5.1/jquery.easyui.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("        <img id=\"logo\" src=\"images/LOGO.png\">\r\n");
      out.write("        <h1>StreetViewRatingApp</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"form1\">\r\n");
      out.write("\t    <form id=\"ff\" method=\"post\" action=\"");
      out.print(basePath);
      out.write("register\">\r\n");
      out.write("\t    \t<table cellpadding=\"5\">\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>Username:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" type=\"text\" name=\"username\" data-options=\"required:true\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>Password:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" type=\"password\" name=\"password\" data-options=\"required:true\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>Country:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" type=\"text\" name=\"country\" data-options=\"required:true\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>Province:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" type=\"text\" name=\"province\" data-options=\"required:true\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>City:</td>\r\n");
      out.write("                    <td><input class=\"easyui-textbox\" type=\"text\" name=\"city\" data-options=\"required:true\"></input></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Occupation:</td>\r\n");
      out.write("                    <td><input class=\"easyui-textbox\" type=\"text\" name=\"occupation\" data-options=\"required:true\"></input></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>Gender:</td>\r\n");
      out.write("\t    \t\t\t<td>\r\n");
      out.write("\t    \t\t\t\t<select class=\"easyui-combobox\" name=\"gender\" data-options=\"required:true\" style=\"width:160px\">\r\n");
      out.write("                            <option value=\"0\">Male</option>\r\n");
      out.write("                            <option value=\"1\">female</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("\t    \t\t\t</td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Incomelevel:</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <select class=\"easyui-combobox\" name=\"incomelevel\" data-options=\"required:true\" style=\"width:160px\">\r\n");
      out.write("                            <option value=\"1\">high</option>\r\n");
      out.write("                            <option value=\"2\">medium</option>\r\n");
      out.write("                            <option value=\"3\">low</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>Operation:</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"submit\" class=\"easyui-linkbutton\" value=\"Submit\" style=\"width:76px;height:26px\"/>\r\n");
      out.write("            \t    \t<input type=\"button\" class=\"easyui-linkbutton\" onclick=\"clearForm()\" value=\"Clear\" style=\"width:76px;height:26px\"/>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t    \t</table>\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <script>\r\n");
      out.write("\t\tfunction clearForm(){\r\n");
      out.write("\t\t\t$('#ff').form('clear');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("    <footer>Copyright @ 2018 [<span class=\"txt\">WangJiale</span>] Developer<br>High-Performance Spatial Computational Intelligence Lab, <span class=\"txt\">HPSCIL</span></footer>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<form action=\"");
      out.print(basePath);
      out.write("register\" method=\"post\">\r\n");
      out.write("\t    username:\r\n");
      out.write("\t\t<input type=\"text\" name=\"username\" /><br/> \r\n");
      out.write("\t\tpassword:\r\n");
      out.write("\t\t<input type=\"password\" name=\"password\" /><br/> \r\n");
      out.write("\t\tcountry:\r\n");
      out.write("\t\t<input type=\"text\" name=\"country\" /><br/> \r\n");
      out.write("\t\tprovince:\r\n");
      out.write("\t\t<input type=\"text\" name=\"province\" /><br/> \r\n");
      out.write("\t\tcity:\r\n");
      out.write("\t\t<input type=\"text\" name=\"city\" /><br/> \r\n");
      out.write("\t\toccupation:\r\n");
      out.write("\t\t<input type=\"text\" name=\"occupation\" /><br/> \r\n");
      out.write("\t\tgender:\r\n");
      out.write("\t\t<label><input type=\"radio\" name=\"gender\" value=\"0\"/>male</label>\r\n");
      out.write("\t\t<label><input type=\"radio\" name=\"gender\" value=\"1\"/>female</label><br/>\r\n");
      out.write("\t\tincomelevel:\r\n");
      out.write("\t\t<select name=\"incomelevel\">\r\n");
      out.write("\t\t\t<option>-请选择-</option>\r\n");
      out.write("\t\t\t<option value=\"1\">high</option>\r\n");
      out.write("\t\t\t<option value=\"2\">medium</option>\r\n");
      out.write("\t\t\t<option value=\"3\">low</option>\r\n");
      out.write("\t\t</select><br/> \r\n");
      out.write("\t\t<input type=\"submit\" value=\"确认\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
